"""Fixture catalogue behind MockProvider.

Thirty-two products chosen to exercise the decisions the platform has to get
right, not to look good in a demo. Roughly a third are traps: false matches,
pack and size mismatches, a price that is low because the listing is about to go
out of stock, a product with three price observations pretending to be a trend.

Every UPC here is check-digit valid, computed at import rather than typed, so the
identity engine is exercised against real identifiers.

Nothing in this module is market data. MockProvider reports ``is_live = False``
and the API surfaces that flag on every response built from it.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from decimal import Decimal

from app.domains.identity.normalization import gtin_check_digit
from app.models.enums import Availability, Marketplace


def _upc(base11: str) -> str:
    """Complete an 11-digit body into a valid UPC-A."""
    if len(base11) != 11 or not base11.isdigit():
        raise ValueError(f"UPC body must be 11 digits: {base11!r}")
    return base11 + str(gtin_check_digit(base11))


@dataclass(frozen=True)
class FixtureListing:
    marketplace: Marketplace
    external_id: str
    title: str
    price: Decimal
    shipping: Decimal = Decimal("0")
    availability: Availability = Availability.IN_STOCK
    seller_count: int | None = 3
    offer_count: int | None = 4
    sales_rank: int | None = None
    rank_category: str | None = None
    review_count: int | None = None
    rating: Decimal | None = None
    quantity_available: int | None = None
    #: Overrides the product's UPC. None keeps the shared identifier; a distinct
    #: value is how a trap listing is made to look similar but identify differently.
    upc: str | None = None
    #: When False the listing carries no GTIN at all, forcing the matcher down to
    #: weaker evidence.
    has_upc: bool = True
    mpn: str | None = None
    condition: str = "new"
    pack_count: int | None = None
    attributes: dict[str, str] = field(default_factory=dict)
    #: Number of days of price history available. Small values are deliberate.
    history_days: int = 180
    #: Daily volatility as a share of price.
    volatility: Decimal = Decimal("0.04")
    #: Total drift across the window, as a share of price.
    trend: Decimal = Decimal("0")
    #: Applied to the most recent observation only, to stage an anomaly.
    latest_shock: Decimal = Decimal("0")
    #: Seller count at the start of the window, for competition trend.
    seller_count_start: int | None = None
    demand_available: bool = True


@dataclass(frozen=True)
class FixtureProduct:
    key: str
    brand: str
    category: str
    upc: str
    weight_lb: Decimal
    listings: tuple[FixtureListing, ...]
    #: What this fixture is here to test. Shown in the seeded data so a failing
    #: expectation is traceable to intent.
    scenario: str
    expectation: str
    mpn: str | None = None
    model: str | None = None
    cubic_feet: Decimal | None = None

    def listing(self, marketplace: Marketplace) -> FixtureListing | None:
        return next((item for item in self.listings if item.marketplace is marketplace), None)


A = Marketplace.AMAZON
W = Marketplace.WALMART


FIXTURES: tuple[FixtureProduct, ...] = (
    # ---------------------------------------------------------------- profitable
    FixtureProduct(
        key="sony-wh1000xm5",
        brand="Sony",
        category="electronics",
        upc=_upc("02724292305"),
        weight_lb=Decimal("1.3"),
        mpn="WH1000XM5/B",
        model="WH-1000XM5",
        scenario="profitable",
        expectation="Clean GTIN match, healthy spread, stable history: should reach BUY.",
        listings=(
            FixtureListing(
                A,
                "B09XS7JWHH",
                "Sony WH-1000XM5 Wireless Noise Cancelling Headphones, Black",
                Decimal("328.00"),
                sales_rank=142,
                rank_category="Electronics",
                review_count=48210,
                rating=Decimal("4.6"),
                seller_count=6,
                offer_count=9,
                mpn="WH1000XM5/B",
                history_days=365,
                volatility=Decimal("0.03"),
                attributes={"color": "black"},
            ),
            FixtureListing(
                W,
                "WM-598712344",
                "Sony WH1000XM5 Wireless Noise Cancelling Headphones Black",
                Decimal("219.00"),
                sales_rank=900,
                rank_category="Electronics",
                review_count=1820,
                rating=Decimal("4.5"),
                seller_count=2,
                offer_count=2,
                quantity_available=40,
                mpn="WH1000XM5/B",
                history_days=210,
                volatility=Decimal("0.05"),
                attributes={"color": "black"},
            ),
        ),
    ),
    FixtureProduct(
        key="instant-pot-duo-6qt",
        brand="Instant Pot",
        category="home & kitchen",
        upc=_upc("81949802031"),
        weight_lb=Decimal("11.8"),
        model="Duo 6 qt",
        cubic_feet=Decimal("1.1"),
        scenario="profitable",
        expectation="Heavy unit: fulfilment and storage eat most of the raw spread.",
        listings=(
            FixtureListing(
                A,
                "B08PQ2KWHS",
                "Instant Pot Duo 7-in-1 Electric Pressure Cooker, 6 Quart",
                Decimal("119.95"),
                sales_rank=88,
                rank_category="Home & Kitchen",
                review_count=201455,
                rating=Decimal("4.7"),
                seller_count=4,
                history_days=365,
                volatility=Decimal("0.06"),
            ),
            FixtureListing(
                W,
                "WM-401882910",
                "Instant Pot Duo 7-in-1 Electric Pressure Cooker 6 Qt",
                Decimal("79.00"),
                sales_rank=1500,
                rank_category="Kitchen",
                review_count=9800,
                rating=Decimal("4.6"),
                seller_count=1,
                quantity_available=25,
                history_days=240,
                volatility=Decimal("0.07"),
            ),
        ),
    ),
    FixtureProduct(
        key="lego-icons-orchid",
        brand="LEGO",
        category="toys & games",
        upc=_upc("67341911872"),
        weight_lb=Decimal("1.9"),
        model="10311",
        scenario="profitable",
        expectation="Strong demand, low competition, modest but real margin.",
        listings=(
            FixtureListing(
                A,
                "B09QSHD8JM",
                "LEGO Icons Orchid 10311 Artificial Plant Building Set",
                Decimal("49.99"),
                sales_rank=310,
                rank_category="Toys & Games",
                review_count=15600,
                rating=Decimal("4.8"),
                seller_count=5,
                history_days=365,
                volatility=Decimal("0.04"),
            ),
            FixtureListing(
                W,
                "WM-773410288",
                "LEGO Icons Orchid 10311 Building Set, 608 Pieces",
                Decimal("27.97"),
                sales_rank=2100,
                review_count=430,
                rating=Decimal("4.8"),
                seller_count=1,
                quantity_available=60,
                history_days=180,
            ),
        ),
    ),
    FixtureProduct(
        key="ninja-air-fryer-af101",
        brand="Ninja",
        category="home & kitchen",
        upc=_upc("62235900158"),
        weight_lb=Decimal("10.3"),
        model="AF101",
        cubic_feet=Decimal("0.9"),
        scenario="profitable",
        expectation="Comfortable ROI with an ordinary fee load.",
        listings=(
            FixtureListing(
                A,
                "B07FDJMC9Q",
                "Ninja AF101 Air Fryer, 4 Quart, Grey",
                Decimal("99.99"),
                sales_rank=52,
                rank_category="Home & Kitchen",
                review_count=78900,
                rating=Decimal("4.8"),
                seller_count=7,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-118820043",
                "Ninja AF101 Air Fryer 4 Qt, Grey",
                Decimal("56.00"),
                sales_rank=1400,
                review_count=5600,
                seller_count=2,
                quantity_available=18,
                history_days=200,
            ),
        ),
    ),
    FixtureProduct(
        key="cerave-moisturizing-cream",
        brand="CeraVe",
        category="beauty",
        upc=_upc("30177211104"),
        weight_lb=Decimal("1.4"),
        scenario="unprofitable",
        expectation=(
            "Low-ticket consumable with a healthy-looking spread. Per-unit fulfilment "
            "exceeds it outright: the classic false positive of a spread-only tool."
        ),
        listings=(
            FixtureListing(
                A,
                "B00TTD9BRC",
                "CeraVe Moisturizing Cream 19 oz Daily Face and Body Moisturizer",
                Decimal("19.88"),
                sales_rank=15,
                rank_category="Beauty",
                review_count=132000,
                rating=Decimal("4.8"),
                seller_count=12,
                history_days=365,
                volatility=Decimal("0.05"),
            ),
            FixtureListing(
                W,
                "WM-220945551",
                "CeraVe Moisturizing Cream, 19 oz",
                Decimal("13.42"),
                sales_rank=800,
                review_count=8900,
                seller_count=1,
                quantity_available=120,
                history_days=210,
            ),
        ),
    ),
    FixtureProduct(
        key="anker-737-powerbank",
        brand="Anker",
        category="electronics",
        upc=_upc("19406807715"),
        weight_lb=Decimal("1.4"),
        mpn="A1289",
        scenario="profitable",
        expectation="Electronics referral rate is low, so margin survives a small spread.",
        listings=(
            FixtureListing(
                A,
                "B09VPHVT2Z",
                "Anker 737 Power Bank PowerCore 24K, 140W Portable Charger",
                Decimal("109.99"),
                sales_rank=420,
                rank_category="Electronics",
                review_count=12400,
                rating=Decimal("4.6"),
                seller_count=3,
                mpn="A1289",
                history_days=300,
            ),
            FixtureListing(
                W,
                "WM-556120388",
                "Anker 737 PowerCore 24K Power Bank 140W",
                Decimal("79.00"),
                sales_rank=3200,
                review_count=210,
                seller_count=1,
                quantity_available=30,
                mpn="A1289",
                history_days=150,
            ),
        ),
    ),
    # -------------------------------------------------------------- unprofitable
    FixtureProduct(
        key="hydroflask-32oz",
        brand="Hydro Flask",
        category="sports & outdoors",
        upc=_upc("81047710403"),
        weight_lb=Decimal("1.6"),
        scenario="unprofitable",
        expectation="Spread looks fine, fees erase it: must not be a BUY.",
        listings=(
            FixtureListing(
                A,
                "B083GBLGZR",
                "Hydro Flask 32 oz Wide Mouth Water Bottle, Black",
                Decimal("39.95"),
                sales_rank=640,
                rank_category="Sports & Outdoors",
                review_count=42100,
                rating=Decimal("4.8"),
                seller_count=9,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-908123774",
                "Hydro Flask 32 oz Wide Mouth Bottle Black",
                Decimal("34.88"),
                sales_rank=4100,
                review_count=620,
                seller_count=3,
                quantity_available=15,
                history_days=180,
            ),
        ),
    ),
    FixtureProduct(
        key="dyson-v15",
        brand="Dyson",
        category="home & kitchen",
        upc=_upc("88580900214"),
        weight_lb=Decimal("14.2"),
        cubic_feet=Decimal("2.4"),
        scenario="unprofitable",
        expectation="Negative profit at the observed prices; bulky storage compounds it.",
        listings=(
            FixtureListing(
                A,
                "B0BF2Y4X5W",
                "Dyson V15 Detect Cordless Vacuum Cleaner, Yellow/Nickel",
                Decimal("649.99"),
                sales_rank=230,
                rank_category="Home & Kitchen",
                review_count=8900,
                rating=Decimal("4.5"),
                seller_count=5,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-334981002",
                "Dyson V15 Detect Cordless Vacuum, Yellow/Nickel",
                Decimal("629.00"),
                sales_rank=7800,
                review_count=340,
                seller_count=2,
                quantity_available=8,
                history_days=160,
            ),
        ),
    ),
    FixtureProduct(
        key="kitchenaid-mixer",
        brand="KitchenAid",
        category="home & kitchen",
        upc=_upc("88301105523"),
        weight_lb=Decimal("26.0"),
        cubic_feet=Decimal("3.1"),
        scenario="unprofitable",
        expectation="Weight tier dominates: a 26 lb unit at a 5% spread is a loss.",
        listings=(
            FixtureListing(
                A,
                "B00063ULMI",
                "KitchenAid Artisan Series 5 Qt Tilt-Head Stand Mixer, Empire Red",
                Decimal("449.99"),
                sales_rank=190,
                rank_category="Home & Kitchen",
                review_count=33000,
                rating=Decimal("4.8"),
                seller_count=6,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-660012388",
                "KitchenAid Artisan 5 Quart Stand Mixer Empire Red",
                Decimal("429.00"),
                sales_rank=5600,
                review_count=890,
                seller_count=2,
                quantity_available=12,
                history_days=200,
            ),
        ),
    ),
    FixtureProduct(
        key="bose-qc-ultra",
        brand="Bose",
        category="electronics",
        upc=_upc("01777119384"),
        weight_lb=Decimal("1.5"),
        scenario="unprofitable",
        expectation="Source is more expensive than the target: negative spread.",
        listings=(
            FixtureListing(
                A,
                "B0CCZ1LMY3",
                "Bose QuietComfort Ultra Wireless Headphones, Black",
                Decimal("349.00"),
                sales_rank=280,
                rank_category="Electronics",
                review_count=9800,
                rating=Decimal("4.5"),
                seller_count=4,
                history_days=300,
            ),
            FixtureListing(
                W,
                "WM-771205663",
                "Bose QuietComfort Ultra Headphones Black",
                Decimal("379.00"),
                sales_rank=9100,
                review_count=120,
                seller_count=1,
                quantity_available=22,
                history_days=140,
            ),
        ),
    ),
    # ----------------------------------------------------------- false matches
    FixtureProduct(
        key="airpods-pro-generation-trap",
        brand="Apple",
        category="electronics",
        upc=_upc("19425299134"),
        weight_lb=Decimal("0.6"),
        scenario="false_match",
        expectation="2nd gen vs 1st gen with different GTINs: must be rejected.",
        listings=(
            FixtureListing(
                A,
                "B0CHWRXH8B",
                "Apple AirPods Pro (2nd Generation) with MagSafe Case USB-C",
                Decimal("189.00"),
                sales_rank=3,
                rank_category="Electronics",
                review_count=98000,
                rating=Decimal("4.7"),
                seller_count=8,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-100238844",
                "Apple AirPods Pro (1st Generation) with Wireless Charging Case",
                Decimal("129.00"),
                upc=_upc("19019172641"),
                sales_rank=2400,
                review_count=4300,
                seller_count=3,
                quantity_available=40,
                history_days=200,
            ),
        ),
    ),
    FixtureProduct(
        key="xm5-vs-xm4-trap",
        brand="Sony",
        category="electronics",
        upc=_upc("02724293607"),
        weight_lb=Decimal("1.3"),
        scenario="false_match",
        expectation="Near-identical titles, different model: title similarity must not carry it.",
        listings=(
            FixtureListing(
                A,
                "B0863TXGM3",
                "Sony WH-1000XM4 Wireless Noise Cancelling Headphones, Black",
                Decimal("248.00"),
                has_upc=False,
                sales_rank=390,
                rank_category="Electronics",
                review_count=61000,
                rating=Decimal("4.7"),
                seller_count=7,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-598712999",
                "Sony WH-1000XM5 Wireless Noise Cancelling Headphones Black",
                Decimal("248.00"),
                has_upc=False,
                sales_rank=1900,
                review_count=760,
                seller_count=2,
                quantity_available=15,
                history_days=150,
            ),
        ),
    ),
    FixtureProduct(
        key="switch-oled-accessory-trap",
        brand="Nintendo",
        category="video games",
        upc=_upc("04549666238"),
        weight_lb=Decimal("2.0"),
        scenario="false_match",
        expectation="Console vs carrying case: accessory detection must reject it.",
        listings=(
            FixtureListing(
                A,
                "B098RKWHHZ",
                "Nintendo Switch OLED Model Console with White Joy-Con",
                Decimal("349.00"),
                has_upc=False,
                sales_rank=12,
                rank_category="Video Games",
                review_count=45000,
                rating=Decimal("4.8"),
                seller_count=10,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-885010223",
                "Carrying Case for Nintendo Switch OLED Model, Hard Shell White",
                Decimal("18.99"),
                has_upc=False,
                sales_rank=8800,
                review_count=210,
                seller_count=4,
                quantity_available=200,
                history_days=120,
            ),
        ),
    ),
    FixtureProduct(
        key="iphone-charger-trap",
        brand="Apple",
        category="cell phone accessories",
        upc=_upc("19425291557"),
        weight_lb=Decimal("0.3"),
        scenario="false_match",
        expectation="Product vs 'compatible with' third-party item.",
        listings=(
            FixtureListing(
                A,
                "B0BSHF7LLL",
                "Apple 20W USB-C Power Adapter",
                Decimal("18.99"),
                sales_rank=45,
                rank_category="Cell Phone Accessories",
                review_count=88000,
                rating=Decimal("4.8"),
                seller_count=14,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-443981002",
                "20W USB-C Fast Charger Compatible with iPhone, 2-Pack",
                Decimal("9.88"),
                upc=_upc("84210087719"),
                pack_count=2,
                sales_rank=6200,
                review_count=1400,
                seller_count=6,
                quantity_available=500,
                history_days=120,
            ),
        ),
    ),
    # ------------------------------------------------------------ pack mismatch
    FixtureProduct(
        key="tide-pods-pack-trap",
        brand="Tide",
        category="grocery",
        upc=_upc("03700085806"),
        weight_lb=Decimal("3.4"),
        scenario="pack_mismatch",
        expectation="42-count vs 112-count: the spread is an illusion of pack size.",
        listings=(
            FixtureListing(
                A,
                "B078JXWDVX",
                "Tide PODS Laundry Detergent Soap Pods, Spring Meadow, 112 count",
                Decimal("31.94"),
                pack_count=112,
                sales_rank=22,
                rank_category="Grocery",
                review_count=112000,
                rating=Decimal("4.8"),
                seller_count=8,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-220884411",
                "Tide PODS Laundry Detergent Pacs, Spring Meadow, 42 count",
                Decimal("12.97"),
                upc=_upc("03700091103"),
                pack_count=42,
                sales_rank=900,
                review_count=6700,
                seller_count=1,
                quantity_available=300,
                history_days=180,
            ),
        ),
    ),
    FixtureProduct(
        key="aa-batteries-pack-trap",
        brand="Energizer",
        category="electronics",
        upc=_upc("03980029119"),
        weight_lb=Decimal("1.1"),
        scenario="pack_mismatch",
        expectation="One side declares a 24-pack, the other declares nothing: block it.",
        listings=(
            FixtureListing(
                A,
                "B004X9WYHY",
                "Energizer MAX AA Batteries, 24 Pack Alkaline Batteries",
                Decimal("21.49"),
                pack_count=24,
                sales_rank=8,
                rank_category="Electronics",
                review_count=201000,
                rating=Decimal("4.8"),
                seller_count=11,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-331882004",
                "Energizer MAX AA Alkaline Batteries",
                Decimal("6.44"),
                has_upc=False,
                sales_rank=1200,
                review_count=4100,
                seller_count=2,
                quantity_available=400,
                history_days=180,
            ),
        ),
    ),
    FixtureProduct(
        key="coffee-pods-pack-trap",
        brand="Starbucks",
        category="grocery",
        upc=_upc("76226800042"),
        weight_lb=Decimal("2.2"),
        scenario="pack_mismatch",
        expectation="Pack of 72 vs pack of 24 at a similar unit economics profile.",
        listings=(
            FixtureListing(
                A,
                "B00PF5SJEG",
                "Starbucks Pike Place K-Cup Coffee Pods, 72 count",
                Decimal("44.99"),
                pack_count=72,
                sales_rank=120,
                rank_category="Grocery",
                review_count=54000,
                rating=Decimal("4.7"),
                seller_count=6,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-661200388",
                "Starbucks Pike Place Roast K-Cup Pods, 24 count",
                Decimal("16.98"),
                upc=_upc("76226800103"),
                pack_count=24,
                sales_rank=2200,
                review_count=3100,
                seller_count=2,
                quantity_available=150,
                history_days=180,
            ),
        ),
    ),
    # ----------------------------------------------------------- size mismatch
    FixtureProduct(
        key="sandisk-capacity-trap",
        brand="SanDisk",
        category="computers",
        upc=_upc("61965917722"),
        weight_lb=Decimal("0.2"),
        scenario="size_mismatch",
        expectation="256 GB vs 128 GB: capacity conflict must block the match.",
        listings=(
            FixtureListing(
                A,
                "B09X7MPX8L",
                "SanDisk 256GB Ultra microSDXC UHS-I Memory Card",
                Decimal("24.99"),
                sales_rank=30,
                rank_category="Computers",
                review_count=310000,
                rating=Decimal("4.7"),
                seller_count=13,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-772001884",
                "SanDisk 128GB Ultra microSDXC UHS-I Memory Card",
                Decimal("12.88"),
                upc=_upc("61965917623"),
                sales_rank=1800,
                review_count=8800,
                seller_count=3,
                quantity_available=250,
                history_days=180,
            ),
        ),
    ),
    FixtureProduct(
        key="olaplex-size-trap",
        brand="Olaplex",
        category="beauty",
        upc=_upc("85067900726"),
        weight_lb=Decimal("1.2"),
        scenario="size_mismatch",
        expectation="8.5 fl oz vs 3.3 fl oz of the same product line.",
        listings=(
            FixtureListing(
                A,
                "B00SNM5USK",
                "Olaplex No. 3 Hair Perfector Treatment, 8.5 fl oz",
                Decimal("54.00"),
                sales_rank=60,
                rank_category="Beauty",
                review_count=44000,
                rating=Decimal("4.5"),
                seller_count=9,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-119920043",
                "Olaplex No. 3 Hair Perfector, 3.3 fl oz",
                Decimal("28.00"),
                upc=_upc("85067900801"),
                sales_rank=3400,
                review_count=1200,
                seller_count=2,
                quantity_available=60,
                history_days=150,
            ),
        ),
    ),
    # ---------------------------------------------------------- colour mismatch
    FixtureProduct(
        key="stanley-tumbler-color-trap",
        brand="Stanley",
        category="home & kitchen",
        upc=_upc("04113806724"),
        weight_lb=Decimal("1.8"),
        scenario="color_mismatch",
        expectation=(
            "Same model, different colourway. A soft conflict rather than a rejection, "
            "which leaves identity AMBIGUOUS: not proven wrong, not proven right."
        ),
        listings=(
            FixtureListing(
                A,
                "B0CRMZHDG8",
                "Stanley Quencher H2.0 FlowState Tumbler 40 oz, Rose Quartz",
                Decimal("49.95"),
                has_upc=False,
                sales_rank=25,
                rank_category="Home & Kitchen",
                review_count=88000,
                rating=Decimal("4.6"),
                seller_count=15,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-882100455",
                "Stanley Quencher H2.0 FlowState Tumbler 40 oz, Charcoal",
                Decimal("34.97"),
                has_upc=False,
                sales_rank=1500,
                review_count=5600,
                seller_count=3,
                quantity_available=90,
                history_days=180,
            ),
        ),
    ),
    # ----------------------------------------------------------- price anomaly
    FixtureProduct(
        key="crest-whitestrips-anomaly",
        brand="Crest",
        category="health & personal care",
        upc=_upc("03700041267"),
        weight_lb=Decimal("0.9"),
        scenario="price_anomaly",
        expectation="Source price 45% under its own median: cheap for a reason, needs REVIEW.",
        listings=(
            FixtureListing(
                A,
                "B00A2EWD1O",
                "Crest 3D Whitestrips Professional Effects, 22 Treatments",
                Decimal("45.99"),
                sales_rank=40,
                rank_category="Health & Personal Care",
                review_count=95000,
                rating=Decimal("4.5"),
                seller_count=8,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-440129983",
                "Crest 3D Whitestrips Professional Effects, 22 Treatments",
                Decimal("13.75"),
                sales_rank=2800,
                review_count=3400,
                seller_count=1,
                quantity_available=4,
                availability=Availability.LIMITED,
                history_days=240,
                latest_shock=Decimal("-0.45"),
            ),
        ),
    ),
    FixtureProduct(
        key="graco-carseat-collapse",
        brand="Graco",
        category="baby",
        upc=_upc("04784616600"),
        weight_lb=Decimal("19.0"),
        cubic_feet=Decimal("3.8"),
        scenario="price_anomaly",
        expectation="Target price collapsed in the last day: the exit price is not real yet.",
        listings=(
            FixtureListing(
                A,
                "B07DPXG7GX",
                "Graco Extend2Fit Convertible Car Seat, Gotham",
                Decimal("199.99"),
                sales_rank=95,
                rank_category="Baby",
                review_count=28000,
                rating=Decimal("4.8"),
                seller_count=5,
                history_days=365,
                latest_shock=Decimal("-0.38"),
            ),
            FixtureListing(
                W,
                "WM-220771003",
                "Graco Extend2Fit Convertible Car Seat, Gotham",
                Decimal("149.00"),
                sales_rank=3100,
                review_count=900,
                seller_count=2,
                quantity_available=20,
                history_days=200,
            ),
        ),
    ),
    FixtureProduct(
        key="lego-star-wars-spike",
        brand="LEGO",
        category="toys & games",
        upc=_upc("67341916051"),
        weight_lb=Decimal("4.4"),
        scenario="price_anomaly",
        expectation="Target price spiked well above its median: the exit assumption is fragile.",
        listings=(
            FixtureListing(
                A,
                "B0B4DJ3M8X",
                "LEGO Star Wars Millennium Falcon 75375 Building Set",
                Decimal("128.00"),
                sales_rank=210,
                rank_category="Toys & Games",
                review_count=6100,
                rating=Decimal("4.9"),
                seller_count=6,
                history_days=300,
                latest_shock=Decimal("0.42"),
            ),
            FixtureListing(
                W,
                "WM-551209911",
                "LEGO Star Wars Millennium Falcon 75375",
                Decimal("79.00"),
                sales_rank=4400,
                review_count=280,
                seller_count=1,
                quantity_available=14,
                history_days=180,
            ),
        ),
    ),
    # ------------------------------------------------------- high competition
    FixtureProduct(
        key="airtag-4pack-competition",
        brand="Apple",
        category="electronics",
        upc=_upc("19425224498"),
        weight_lb=Decimal("0.5"),
        scenario="high_competition",
        expectation="Seller count nearly tripled in 30 days: margin will not survive.",
        listings=(
            FixtureListing(
                A,
                "B0932QJ2JZ",
                "Apple AirTag 4 Pack",
                Decimal("79.00"),
                pack_count=4,
                sales_rank=18,
                rank_category="Electronics",
                review_count=142000,
                rating=Decimal("4.7"),
                seller_count=34,
                seller_count_start=11,
                offer_count=41,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-661002884",
                "Apple AirTag 4 Pack Bluetooth Item Finder",
                Decimal("64.00"),
                pack_count=4,
                sales_rank=2600,
                review_count=5100,
                seller_count=9,
                seller_count_start=4,
                quantity_available=80,
                history_days=200,
            ),
        ),
    ),
    FixtureProduct(
        key="fire-tv-stick-competition",
        brand="Amazon",
        category="electronics",
        upc=_upc("84093934660"),
        weight_lb=Decimal("0.4"),
        scenario="high_competition",
        expectation="Marketplace itself is the buy-box seller: competing is a losing game.",
        listings=(
            FixtureListing(
                A,
                "B0BP9MDCQZ",
                "Amazon Fire TV Stick 4K Max Streaming Device",
                Decimal("39.99"),
                sales_rank=2,
                rank_category="Electronics",
                review_count=410000,
                rating=Decimal("4.6"),
                seller_count=22,
                seller_count_start=18,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-118829930",
                "Amazon Fire TV Stick 4K Max Streaming Media Player",
                Decimal("32.88"),
                sales_rank=5100,
                review_count=2200,
                seller_count=6,
                quantity_available=45,
                history_days=180,
            ),
        ),
    ),
    # ---------------------------------------------------------- low inventory
    FixtureProduct(
        key="vitamix-a3500-low-stock",
        brand="Vitamix",
        category="home & kitchen",
        upc=_upc("70362600724"),
        weight_lb=Decimal("13.5"),
        cubic_feet=Decimal("2.0"),
        scenario="low_inventory",
        expectation="Only 2 units at the source price: position size must be capped.",
        listings=(
            FixtureListing(
                A,
                "B076GYR6SP",
                "Vitamix A3500 Ascent Series Smart Blender, Brushed Stainless",
                Decimal("599.95"),
                sales_rank=450,
                rank_category="Home & Kitchen",
                review_count=7800,
                rating=Decimal("4.7"),
                seller_count=4,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-993012004",
                "Vitamix A3500 Ascent Smart Blender Brushed Stainless",
                Decimal("429.00"),
                sales_rank=8800,
                review_count=140,
                seller_count=1,
                quantity_available=2,
                availability=Availability.LIMITED,
                history_days=150,
            ),
        ),
    ),
    FixtureProduct(
        key="theragun-mini-low-stock",
        brand="Therabody",
        category="health & personal care",
        upc=_upc("85002600616"),
        weight_lb=Decimal("1.9"),
        scenario="low_inventory",
        expectation="Limited availability alongside a strong spread: REVIEW, not BUY.",
        listings=(
            FixtureListing(
                A,
                "B08L5QYGPX",
                "Therabody Theragun Mini Handheld Percussive Massage Device",
                Decimal("199.00"),
                sales_rank=520,
                rank_category="Health & Personal Care",
                review_count=9400,
                rating=Decimal("4.6"),
                seller_count=5,
                history_days=300,
            ),
            FixtureListing(
                W,
                "WM-220019984",
                "Theragun Mini Handheld Percussive Massage Device",
                Decimal("129.00"),
                sales_rank=6100,
                review_count=420,
                seller_count=1,
                quantity_available=3,
                availability=Availability.LIMITED,
                history_days=160,
            ),
        ),
    ),
    # ------------------------------------------------------------ weak demand
    FixtureProduct(
        key="obscure-niche-tool-weak-demand",
        brand="Bosch",
        category="tools & home improvement",
        upc=_upc("00034609934"),
        weight_lb=Decimal("5.2"),
        scenario="weak_demand",
        expectation="Excellent margin, rank near a million: capital would sit still.",
        listings=(
            FixtureListing(
                A,
                "B08XYZQ1RT",
                "Bosch GLM 165-40 Blaze Laser Distance Measure 165 ft",
                Decimal("129.00"),
                sales_rank=842000,
                rank_category="Tools & Home Improvement",
                review_count=42,
                rating=Decimal("4.3"),
                seller_count=2,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-770012883",
                "Bosch GLM 165-40 Blaze Laser Distance Measurer 165 ft",
                Decimal("74.00"),
                sales_rank=91000,
                review_count=6,
                seller_count=1,
                quantity_available=9,
                history_days=140,
            ),
        ),
    ),
    FixtureProduct(
        key="seasonal-decor-weak-demand",
        brand="Ashland",
        category="home & kitchen",
        upc=_upc("19271055507"),
        weight_lb=Decimal("2.8"),
        scenario="weak_demand",
        expectation="Review velocity is flat: no evidence the unit moves at all.",
        listings=(
            FixtureListing(
                A,
                "B09TTQ4KLM",
                "Ashland Ceramic Pumpkin Decor Set of 3, Autumn Harvest",
                Decimal("44.99"),
                sales_rank=410000,
                rank_category="Home & Kitchen",
                review_count=18,
                rating=Decimal("4.0"),
                seller_count=3,
                pack_count=3,
                history_days=240,
            ),
            FixtureListing(
                W,
                "WM-118820991",
                "Ashland Ceramic Pumpkin Decor, Set of 3, Autumn Harvest",
                Decimal("24.00"),
                sales_rank=120000,
                review_count=2,
                seller_count=1,
                pack_count=3,
                quantity_available=30,
                history_days=120,
            ),
        ),
    ),
    # ---------------------------------------------------------- missing data
    FixtureProduct(
        key="new-release-thin-history",
        brand="Shark",
        category="home & kitchen",
        upc=_upc("62235911304"),
        weight_lb=Decimal("9.1"),
        scenario="missing_data",
        expectation="Three price observations. Must not be shown as a trend.",
        listings=(
            FixtureListing(
                A,
                "B0CX1Y2Z3Q",
                "Shark FlexStyle Air Styling and Drying System",
                Decimal("279.00"),
                sales_rank=1200,
                rank_category="Home & Kitchen",
                review_count=340,
                rating=Decimal("4.4"),
                seller_count=3,
                history_days=3,
            ),
            FixtureListing(
                W,
                "WM-551002993",
                "Shark FlexStyle Air Styling & Drying System",
                Decimal("199.00"),
                sales_rank=None,
                review_count=None,
                seller_count=1,
                quantity_available=25,
                history_days=2,
                demand_available=False,
            ),
        ),
    ),
    FixtureProduct(
        key="no-demand-data-product",
        brand="Generic",
        category="office products",
        upc=_upc("01234567890"),
        weight_lb=Decimal("2.1"),
        scenario="missing_data",
        expectation="No rank on either side: demand confidence must read NONE, not zero.",
        listings=(
            FixtureListing(
                A,
                "B0AAA111BB",
                "Heavy Duty Stapler 100 Sheet Capacity, Black",
                Decimal("34.99"),
                sales_rank=None,
                review_count=None,
                seller_count=2,
                demand_available=False,
                history_days=90,
            ),
            FixtureListing(
                W,
                "WM-000112233",
                "Heavy Duty Stapler 100 Sheet Capacity Black",
                Decimal("18.50"),
                sales_rank=None,
                review_count=None,
                seller_count=1,
                quantity_available=40,
                demand_available=False,
                history_days=60,
            ),
        ),
    ),
    FixtureProduct(
        key="no-target-listing",
        brand="Zojirushi",
        category="home & kitchen",
        upc=_upc("07640507720"),
        weight_lb=Decimal("8.4"),
        scenario="missing_data",
        expectation="Source only. There is no opportunity without an exit market.",
        listings=(
            FixtureListing(
                A,
                "B00E2RGPFS",
                "Zojirushi NS-TSC10 Micom Rice Cooker and Warmer, 5.5 Cup",
                Decimal("214.99"),
                sales_rank=980,
                rank_category="Home & Kitchen",
                review_count=12000,
                rating=Decimal("4.7"),
                seller_count=3,
                history_days=365,
            ),
        ),
    ),
    # -------------------------------------------------------------- high risk
    FixtureProduct(
        key="volatile-gpu-high-risk",
        brand="NVIDIA",
        category="computers",
        upc=_upc("81236501109"),
        weight_lb=Decimal("4.6"),
        scenario="high_risk",
        expectation="Large spread, violent price history: volatility must dominate the score.",
        listings=(
            FixtureListing(
                A,
                "B0BG94PS2F",
                "NVIDIA GeForce RTX 4070 Ti Graphics Card 12GB GDDR6X",
                Decimal("799.00"),
                sales_rank=800,
                rank_category="Computers",
                review_count=3400,
                rating=Decimal("4.5"),
                seller_count=12,
                seller_count_start=6,
                history_days=365,
                volatility=Decimal("0.22"),
            ),
            FixtureListing(
                W,
                "WM-882001773",
                "NVIDIA GeForce RTX 4070 Ti 12GB GDDR6X Graphics Card",
                Decimal("569.00"),
                sales_rank=9800,
                review_count=90,
                seller_count=3,
                quantity_available=6,
                history_days=200,
                volatility=Decimal("0.26"),
            ),
        ),
    ),
    FixtureProduct(
        key="gated-brand-high-risk",
        brand="Nike",
        category="clothing",
        upc=_upc("19685908800"),
        weight_lb=Decimal("2.4"),
        scenario="high_risk",
        expectation="High-restriction brand and category: flag it even when the maths works.",
        listings=(
            FixtureListing(
                A,
                "B0C8RQ7YTV",
                "Nike Air Zoom Pegasus 40 Mens Road Running Shoes, Black/White",
                Decimal("129.99"),
                sales_rank=2100,
                rank_category="Clothing",
                review_count=1800,
                rating=Decimal("4.6"),
                seller_count=9,
                history_days=300,
            ),
            FixtureListing(
                W,
                "WM-441200983",
                "Nike Air Zoom Pegasus 40 Men's Running Shoes Black/White",
                Decimal("84.00"),
                sales_rank=7400,
                review_count=210,
                seller_count=2,
                quantity_available=35,
                history_days=180,
            ),
        ),
    ),
    FixtureProduct(
        key="used-condition-trap",
        brand="Canon",
        category="electronics",
        upc=_upc("01353518622"),
        weight_lb=Decimal("3.2"),
        scenario="high_risk",
        expectation="Renewed source against a new target: condition conflict must block it.",
        listings=(
            FixtureListing(
                A,
                "B08DK5ZH3N",
                "Canon EOS M50 Mark II Mirrorless Camera with 15-45mm Lens",
                Decimal("699.00"),
                sales_rank=1400,
                rank_category="Electronics",
                review_count=2900,
                rating=Decimal("4.6"),
                seller_count=5,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-330012884",
                "Canon EOS M50 Mark II Mirrorless Camera 15-45mm, Renewed",
                Decimal("449.00"),
                condition="renewed",
                sales_rank=12000,
                review_count=40,
                seller_count=1,
                quantity_available=5,
                history_days=120,
            ),
        ),
    ),
    FixtureProduct(
        key="thin-margin-borderline",
        brand="Duracell",
        category="electronics",
        upc=_upc("04133337191"),
        weight_lb=Decimal("0.8"),
        scenario="borderline",
        expectation="Sits right on the decision thresholds: exercises REVIEW.",
        listings=(
            FixtureListing(
                A,
                "B00000JHUL",
                "Duracell Coppertop AAA Batteries, 16 Count",
                Decimal("16.99"),
                pack_count=16,
                sales_rank=65,
                rank_category="Electronics",
                review_count=88000,
                rating=Decimal("4.8"),
                seller_count=10,
                history_days=365,
            ),
            FixtureListing(
                W,
                "WM-220003391",
                "Duracell Coppertop AAA Alkaline Batteries, 16 Count",
                Decimal("8.44"),
                pack_count=16,
                sales_rank=1800,
                review_count=5200,
                seller_count=3,
                quantity_available=200,
                history_days=200,
            ),
        ),
    ),
)


FIXTURES_BY_KEY = {fixture.key: fixture for fixture in FIXTURES}

#: marketplace -> external id -> (product, listing)
FIXTURES_BY_EXTERNAL_ID: dict[Marketplace, dict[str, tuple[FixtureProduct, FixtureListing]]] = {}
for _fixture in FIXTURES:
    for _listing in _fixture.listings:
        FIXTURES_BY_EXTERNAL_ID.setdefault(_listing.marketplace, {})[_listing.external_id] = (
            _fixture,
            _listing,
        )


def listing_upc(fixture: FixtureProduct, listing: FixtureListing) -> str | None:
    if not listing.has_upc:
        return None
    return listing.upc or fixture.upc


def deterministic_unit(*parts: object) -> float:
    """A stable pseudo-random float in [0, 1) for the given key parts.

    Seeded by content rather than by a PRNG's global state, so the same fixture
    produces the same history on every process, machine and test run. Reproducible
    fixtures are the difference between a failing test that means something and a
    flaky one.
    """
    digest = hashlib.sha256("|".join(str(part) for part in parts).encode()).digest()
    return int.from_bytes(digest[:8], "big") / float(1 << 64)
