"""initial schema

Revision ID: 25274d26d2a9
Revises:
Create Date: 2026-09-12 08:27:48.990342
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations reference the portable column types (GUID, JSONB) by their module
# path, so the module is always imported.
import app.models.types  # noqa: F401

revision: str = "25274d26d2a9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("settings", app.models.types.JSONB(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organizations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)

    op.create_table(
        "provider_health",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("circuit_state", sa.String(length=16), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("avg_latency_ms", sa.Integer(), nullable=True),
        sa.Column("p95_latency_ms", sa.Integer(), nullable=True),
        sa.Column("rate_limit_per_second", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("quota_limit", sa.Integer(), nullable=True),
        sa.Column("quota_used", sa.Integer(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("circuit_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_health")),
    )
    with op.batch_alter_table("provider_health", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provider_health_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_provider_health_provider"), ["provider"], unique=True)

    op.create_table(
        "provider_requests",
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("was_cached", sa.Boolean(), nullable=False),
        sa.Column("context", app.models.types.JSONB(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_requests")),
    )
    with op.batch_alter_table("provider_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provider_requests_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_provider_requests_provider"), ["provider"], unique=False
        )

    op.create_table(
        "capital_plans",
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("available_capital", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("constraints", app.models.types.JSONB(), nullable=False),
        sa.Column("allocations", app.models.types.JSONB(), nullable=False),
        sa.Column("excluded", app.models.types.JSONB(), nullable=False),
        sa.Column("allocated_capital", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unallocated_capital", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expected_profit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expected_roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("is_simulation", sa.Boolean(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_capital_plans_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capital_plans")),
    )
    with op.batch_alter_table("capital_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_capital_plans_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capital_plans_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "products",
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("brand", sa.String(length=200), nullable=True),
        sa.Column("manufacturer", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("primary_gtin", sa.String(length=14), nullable=True),
        sa.Column("pack_count", sa.Integer(), nullable=True),
        sa.Column("attributes", app.models.types.JSONB(), nullable=False),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_products_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_brand"), ["brand"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_products_org_brand", ["organization_id", "brand"], unique=False)
        batch_op.create_index(
            "ix_products_org_primary_gtin", ["organization_id", "primary_gtin"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_primary_gtin"), ["primary_gtin"], unique=False
        )

    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("preferences", app.models.types.JSONB(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_user_settings_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
        sa.UniqueConstraint("user_id", name="uq_user_settings_user_id"),
    )
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_settings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_settings_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_settings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("organization_id", "email", name="uq_users_org_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "marketplace_listings",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("sku", sa.String(length=120), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("brand", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("pack_count", sa.Integer(), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("current_shipping", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("seller_count", sa.Integer(), nullable=True),
        sa.Column("offer_count", sa.Integer(), nullable=True),
        sa.Column("sales_rank", sa.Integer(), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("raw_attributes", app.models.types.JSONB(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_marketplace_listings_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_marketplace_listings_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplace_listings")),
        sa.UniqueConstraint(
            "organization_id",
            "marketplace",
            "external_id",
            name="uq_marketplace_listings_organization_id",
        ),
    )
    with op.batch_alter_table("marketplace_listings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_marketplace_listings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_listings_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_listings_last_seen_at"), ["last_seen_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_listings_marketplace"), ["marketplace"], unique=False
        )
        batch_op.create_index(
            "ix_marketplace_listings_org_marketplace_product_id",
            ["organization_id", "marketplace", "product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_listings_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_marketplace_listings_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "product_attributes",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.Column("normalized_value", sa.String(length=255), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("numeric_value", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_product_attributes_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_attributes_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_attributes")),
        sa.UniqueConstraint("product_id", "name", name="uq_product_attributes_product_id"),
    )
    with op.batch_alter_table("product_attributes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_attributes_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_attributes_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_attributes_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "product_identifiers",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("identifier_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.Column("normalized_value", sa.String(length=64), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("validation_note", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_product_identifiers_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_identifiers_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_identifiers")),
        sa.UniqueConstraint(
            "product_id", "identifier_type", "value", name="uq_product_identifiers_product_id"
        ),
    )
    with op.batch_alter_table("product_identifiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_identifiers_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_identifiers_normalized_value"),
            ["normalized_value"],
            unique=False,
        )
        batch_op.create_index(
            "ix_product_identifiers_org_identifier_type_value",
            ["organization_id", "identifier_type", "value"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_product_identifiers_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_identifiers_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "competition_history",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("seller_count", sa.Integer(), nullable=True),
        sa.Column("offer_count", sa.Integer(), nullable=True),
        sa.Column("lowest_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("median_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("highest_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("buy_box_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("buy_box_seller_id", sa.String(length=120), nullable=True),
        sa.Column("marketplace_is_seller", sa.Boolean(), nullable=True),
        sa.Column("seller_ids", app.models.types.JSONB(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_competition_history_listing_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_competition_history_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_competition_history_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_history")),
    )
    with op.batch_alter_table("competition_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competition_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_history_listing_id"), ["listing_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_history_marketplace"), ["marketplace"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_history_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_history_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_competition_history_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "demand_history",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("sales_rank", sa.Integer(), nullable=True),
        sa.Column("rank_category", sa.String(length=120), nullable=True),
        sa.Column("estimated_monthly_units", sa.Integer(), nullable=True),
        sa.Column("estimation_basis", sa.String(length=64), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("buy_box_seller_id", sa.String(length=120), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_demand_history_listing_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_demand_history_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_demand_history_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demand_history")),
    )
    with op.batch_alter_table("demand_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_demand_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_demand_history_listing_id"), ["listing_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_demand_history_marketplace"), ["marketplace"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_demand_history_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_demand_history_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_demand_history_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "offers",
        sa.Column("listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("external_offer_id", sa.String(length=120), nullable=True),
        sa.Column("seller_id", sa.String(length=120), nullable=True),
        sa.Column("seller_name", sa.String(length=200), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shipping", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("fulfillment", sa.String(length=16), nullable=True),
        sa.Column("is_buy_box", sa.Boolean(), nullable=False),
        sa.Column("is_marketplace_seller", sa.Boolean(), nullable=False),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("quantity_available", sa.Integer(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_offers_listing_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_offers_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
    )
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offers_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_offers_listing_id"), ["listing_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_offers_observed_at"), ["observed_at"], unique=False)
        batch_op.create_index(
            "ix_offers_org_listing_id_observed_at",
            ["organization_id", "listing_id", "observed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_offers_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_offers_seller_id"), ["seller_id"], unique=False)

    op.create_table(
        "price_history",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shipping", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("landed_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("is_buy_box", sa.Boolean(), nullable=False),
        sa.Column("seller_id", sa.String(length=120), nullable=True),
        sa.Column("seller_name", sa.String(length=200), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_price_history_listing_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_price_history_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_price_history_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
        comment="Append-only price observations. Never updated in place.",
    )
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_price_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_history_listing_id"), ["listing_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_history_marketplace"), ["marketplace"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_history_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_history_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_history_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "product_matches",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("source_listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("target_listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("match_confidence", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("match_method", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("evidence", app.models.types.JSONB(), nullable=False),
        sa.Column("conflicts", app.models.types.JSONB(), nullable=False),
        sa.Column("variation_check_passed", sa.Boolean(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("reviewed_by", sa.String(length=120), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_product_matches_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_matches_product_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_product_matches_source_listing_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_product_matches_target_listing_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_matches")),
        sa.UniqueConstraint(
            "source_listing_id", "target_listing_id", name="uq_product_matches_source_listing_id"
        ),
    )
    with op.batch_alter_table("product_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_matches_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_matches_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_matches_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_matches_source_listing_id"), ["source_listing_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_matches_target_listing_id"), ["target_listing_id"], unique=False
        )

    op.create_table(
        "opportunities",
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("source_listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("target_listing_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("match_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column("sourcing_channel", sa.String(length=32), nullable=False),
        sa.Column("source_marketplace", sa.String(length=32), nullable=False),
        sa.Column("target_marketplace", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("recommendation", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("score_model_version", sa.String(length=32), nullable=True),
        sa.Column("score_components", app.models.types.JSONB(), nullable=False),
        sa.Column("acquisition_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("expected_sale_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("net_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("margin", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("spread", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("match_confidence", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("data_quality_score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("demand_confidence", sa.String(length=16), nullable=False),
        sa.Column("explanation", app.models.types.JSONB(), nullable=False),
        sa.Column("recommended_quantity", sa.Integer(), nullable=True),
        sa.Column("recommended_capital", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=120), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["product_matches.id"],
            name=op.f("fk_opportunities_match_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_opportunities_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_opportunities_product_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_opportunities_source_listing_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_opportunities_target_listing_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_opportunities_analyzed_at"), ["analyzed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_opportunities_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_opportunities_org_product_id", ["organization_id", "product_id"], unique=False
        )
        batch_op.create_index(
            "ix_opportunities_org_status_score",
            ["organization_id", "status", "score"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_opportunities_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_opportunities_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_opportunities_score"), ["score"], unique=False)
        batch_op.create_index(batch_op.f("ix_opportunities_status"), ["status"], unique=False)

    op.create_table(
        "opportunity_events",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=True),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("payload", app.models.types.JSONB(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_opportunity_events_opportunity_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_opportunity_events_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_events")),
    )
    with op.batch_alter_table("opportunity_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_opportunity_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_opportunity_events_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            "ix_opportunity_events_org_opportunity_id_created_at",
            ["organization_id", "opportunity_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_opportunity_events_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "opportunity_validations",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("tested_by", sa.String(length=120), nullable=True),
        sa.Column("tested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_source_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("actual_target_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("actual_availability", sa.String(length=32), nullable=True),
        sa.Column("match_confirmed", sa.Boolean(), nullable=True),
        sa.Column("profit_estimate_correct", sa.Boolean(), nullable=True),
        sa.Column("would_buy", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("predicted_source_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("predicted_target_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("predicted_net_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("predicted_roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("predicted_recommendation", sa.String(length=16), nullable=True),
        sa.Column("source_price_delta", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("target_price_delta", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_opportunity_validations_opportunity_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_opportunity_validations_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_validations")),
    )
    with op.batch_alter_table("opportunity_validations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_opportunity_validations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_opportunity_validations_opportunity_id"),
            ["opportunity_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_opportunity_validations_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "profitability_snapshots",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("scenario", sa.String(length=40), nullable=False),
        sa.Column("target_marketplace", sa.String(length=32), nullable=False),
        sa.Column("fulfillment", sa.String(length=16), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("acquisition_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("acquisition_shipping", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("referral_fee", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("fulfillment_fee", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("closing_fee", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("storage_fee", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("inbound_shipping", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("return_allowance", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tax", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("misc_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("total_fees", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("net_profit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("margin", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("breakeven_sale_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("max_acquisition_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("line_items", app.models.types.JSONB(), nullable=False),
        sa.Column("assumptions", app.models.types.JSONB(), nullable=False),
        sa.Column("assumptions_version", sa.String(length=40), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_profitability_snapshots_opportunity_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_profitability_snapshots_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_profitability_snapshots_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profitability_snapshots")),
    )
    with op.batch_alter_table("profitability_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_profitability_snapshots_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_profitability_snapshots_opportunity_id"),
            ["opportunity_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_profitability_snapshots_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_profitability_snapshots_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "purchases",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("source_marketplace", sa.String(length=32), nullable=True),
        sa.Column("supplier", sa.String(length=200), nullable=True),
        sa.Column("sourcing_channel", sa.String(length=32), nullable=False),
        sa.Column("order_reference", sa.String(length=120), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tax", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("other_costs", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_delivery", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_purchases_opportunity_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_purchases_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchases_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
    )
    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchases_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_purchases_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            "ix_purchases_org_purchased_at", ["organization_id", "purchased_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchases_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_purchases_product_id"), ["product_id"], unique=False)

    op.create_table(
        "risk_assessments",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("scenario", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("signals", app.models.types.JSONB(), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_risk_assessments_opportunity_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_risk_assessments_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_risk_assessments_product_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_assessments")),
    )
    with op.batch_alter_table("risk_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_risk_assessments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_risk_assessments_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_risk_assessments_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_risk_assessments_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "outcomes",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("purchase_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("quantity_purchased", sa.Integer(), nullable=False),
        sa.Column("quantity_sold", sa.Integer(), nullable=False),
        sa.Column("capital_deployed", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("predicted_unit_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("predicted_total_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("predicted_roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("predicted_recommendation", sa.String(length=16), nullable=True),
        sa.Column("predicted_score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("actual_revenue", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("actual_costs", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("actual_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("actual_roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("profit_variance", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("profit_variance_pct", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("roi_variance", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("days_to_sell", sa.Integer(), nullable=True),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_outcomes_opportunity_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_outcomes_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_outcomes_product_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_outcomes_purchase_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outcomes")),
    )
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outcomes_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_outcomes_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outcomes_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_outcomes_product_id"), ["product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_outcomes_purchase_id"), ["purchase_id"], unique=False)

    op.create_table(
        "sales",
        sa.Column("purchase_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("order_reference", sa.String(length=120), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("gross_revenue", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("marketplace_fees", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("fulfillment_fees", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("storage_fees", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("refunds", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("other_costs", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("net_proceeds", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_sales_opportunity_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sales_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_sales_product_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_sales_purchase_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
    )
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sales_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sales_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index("ix_sales_org_sold_at", ["organization_id", "sold_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sales_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sales_product_id"), ["product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sales_purchase_id"), ["purchase_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sales_purchase_id"))
        batch_op.drop_index(batch_op.f("ix_sales_product_id"))
        batch_op.drop_index(batch_op.f("ix_sales_organization_id"))
        batch_op.drop_index("ix_sales_org_sold_at")
        batch_op.drop_index(batch_op.f("ix_sales_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_sales_created_at"))

    op.drop_table("sales")
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outcomes_purchase_id"))
        batch_op.drop_index(batch_op.f("ix_outcomes_product_id"))
        batch_op.drop_index(batch_op.f("ix_outcomes_organization_id"))
        batch_op.drop_index(batch_op.f("ix_outcomes_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_outcomes_created_at"))

    op.drop_table("outcomes")
    with op.batch_alter_table("risk_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_assessments_product_id"))
        batch_op.drop_index(batch_op.f("ix_risk_assessments_organization_id"))
        batch_op.drop_index(batch_op.f("ix_risk_assessments_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_risk_assessments_created_at"))

    op.drop_table("risk_assessments")
    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchases_product_id"))
        batch_op.drop_index(batch_op.f("ix_purchases_organization_id"))
        batch_op.drop_index("ix_purchases_org_purchased_at")
        batch_op.drop_index(batch_op.f("ix_purchases_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_purchases_created_at"))

    op.drop_table("purchases")
    with op.batch_alter_table("profitability_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profitability_snapshots_product_id"))
        batch_op.drop_index(batch_op.f("ix_profitability_snapshots_organization_id"))
        batch_op.drop_index(batch_op.f("ix_profitability_snapshots_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_profitability_snapshots_created_at"))

    op.drop_table("profitability_snapshots")
    with op.batch_alter_table("opportunity_validations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_opportunity_validations_organization_id"))
        batch_op.drop_index(batch_op.f("ix_opportunity_validations_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_opportunity_validations_created_at"))

    op.drop_table("opportunity_validations")
    with op.batch_alter_table("opportunity_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_opportunity_events_organization_id"))
        batch_op.drop_index("ix_opportunity_events_org_opportunity_id_created_at")
        batch_op.drop_index(batch_op.f("ix_opportunity_events_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_opportunity_events_created_at"))

    op.drop_table("opportunity_events")
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_opportunities_status"))
        batch_op.drop_index(batch_op.f("ix_opportunities_score"))
        batch_op.drop_index(batch_op.f("ix_opportunities_product_id"))
        batch_op.drop_index(batch_op.f("ix_opportunities_organization_id"))
        batch_op.drop_index("ix_opportunities_org_status_score")
        batch_op.drop_index("ix_opportunities_org_product_id")
        batch_op.drop_index(batch_op.f("ix_opportunities_created_at"))
        batch_op.drop_index(batch_op.f("ix_opportunities_analyzed_at"))

    op.drop_table("opportunities")
    with op.batch_alter_table("product_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_matches_target_listing_id"))
        batch_op.drop_index(batch_op.f("ix_product_matches_source_listing_id"))
        batch_op.drop_index(batch_op.f("ix_product_matches_product_id"))
        batch_op.drop_index(batch_op.f("ix_product_matches_organization_id"))
        batch_op.drop_index(batch_op.f("ix_product_matches_created_at"))

    op.drop_table("product_matches")
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_history_product_id"))
        batch_op.drop_index(batch_op.f("ix_price_history_organization_id"))
        batch_op.drop_index(batch_op.f("ix_price_history_observed_at"))
        batch_op.drop_index(batch_op.f("ix_price_history_marketplace"))
        batch_op.drop_index(batch_op.f("ix_price_history_listing_id"))
        batch_op.drop_index(batch_op.f("ix_price_history_created_at"))

    op.drop_table("price_history")
    with op.batch_alter_table("offers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offers_seller_id"))
        batch_op.drop_index(batch_op.f("ix_offers_organization_id"))
        batch_op.drop_index("ix_offers_org_listing_id_observed_at")
        batch_op.drop_index(batch_op.f("ix_offers_observed_at"))
        batch_op.drop_index(batch_op.f("ix_offers_listing_id"))
        batch_op.drop_index(batch_op.f("ix_offers_created_at"))

    op.drop_table("offers")
    with op.batch_alter_table("demand_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demand_history_product_id"))
        batch_op.drop_index(batch_op.f("ix_demand_history_organization_id"))
        batch_op.drop_index(batch_op.f("ix_demand_history_observed_at"))
        batch_op.drop_index(batch_op.f("ix_demand_history_marketplace"))
        batch_op.drop_index(batch_op.f("ix_demand_history_listing_id"))
        batch_op.drop_index(batch_op.f("ix_demand_history_created_at"))

    op.drop_table("demand_history")
    with op.batch_alter_table("competition_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_history_product_id"))
        batch_op.drop_index(batch_op.f("ix_competition_history_organization_id"))
        batch_op.drop_index(batch_op.f("ix_competition_history_observed_at"))
        batch_op.drop_index(batch_op.f("ix_competition_history_marketplace"))
        batch_op.drop_index(batch_op.f("ix_competition_history_listing_id"))
        batch_op.drop_index(batch_op.f("ix_competition_history_created_at"))

    op.drop_table("competition_history")
    with op.batch_alter_table("product_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_identifiers_product_id"))
        batch_op.drop_index(batch_op.f("ix_product_identifiers_organization_id"))
        batch_op.drop_index("ix_product_identifiers_org_identifier_type_value")
        batch_op.drop_index(batch_op.f("ix_product_identifiers_normalized_value"))
        batch_op.drop_index(batch_op.f("ix_product_identifiers_created_at"))

    op.drop_table("product_identifiers")
    with op.batch_alter_table("product_attributes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_attributes_product_id"))
        batch_op.drop_index(batch_op.f("ix_product_attributes_organization_id"))
        batch_op.drop_index(batch_op.f("ix_product_attributes_created_at"))

    op.drop_table("product_attributes")
    with op.batch_alter_table("marketplace_listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_marketplace_listings_product_id"))
        batch_op.drop_index(batch_op.f("ix_marketplace_listings_organization_id"))
        batch_op.drop_index("ix_marketplace_listings_org_marketplace_product_id")
        batch_op.drop_index(batch_op.f("ix_marketplace_listings_marketplace"))
        batch_op.drop_index(batch_op.f("ix_marketplace_listings_last_seen_at"))
        batch_op.drop_index(batch_op.f("ix_marketplace_listings_external_id"))
        batch_op.drop_index(batch_op.f("ix_marketplace_listings_created_at"))

    op.drop_table("marketplace_listings")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_organization_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_settings_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_settings_organization_id"))
        batch_op.drop_index(batch_op.f("ix_user_settings_created_at"))

    op.drop_table("user_settings")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_primary_gtin"))
        batch_op.drop_index(batch_op.f("ix_products_organization_id"))
        batch_op.drop_index("ix_products_org_primary_gtin")
        batch_op.drop_index("ix_products_org_brand")
        batch_op.drop_index(batch_op.f("ix_products_created_at"))
        batch_op.drop_index(batch_op.f("ix_products_category"))
        batch_op.drop_index(batch_op.f("ix_products_brand"))

    op.drop_table("products")
    with op.batch_alter_table("capital_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_capital_plans_organization_id"))
        batch_op.drop_index(batch_op.f("ix_capital_plans_created_at"))

    op.drop_table("capital_plans")
    with op.batch_alter_table("provider_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_requests_provider"))
        batch_op.drop_index(batch_op.f("ix_provider_requests_created_at"))

    op.drop_table("provider_requests")
    with op.batch_alter_table("provider_health", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_health_provider"))
        batch_op.drop_index(batch_op.f("ix_provider_health_created_at"))

    op.drop_table("provider_health")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.drop_index(batch_op.f("ix_organizations_created_at"))

    op.drop_table("organizations")
    # ### end Alembic commands ###
