"""Autonomy: policy versioning, agent runs, decisions, positions, breakers.

All new tables; nothing existing is altered.

The shape encodes two rules that the rest of the autonomy layer depends on:

``autonomy_policies`` is append-only. A change writes a new version and
deactivates the old one, so a decision can always be re-read against the rules
it was actually made under rather than against today's.

``autonomy_decisions`` keeps a full evidence snapshot and is never updated. A
blocked decision is recorded as carefully as an authorised one: the refusals are
the evidence that the limits work.

``capital_positions`` covers shadow and live with one shape on purpose. A shadow
position is tracked against the same market data and measured the same way; only
``purchase_id`` distinguishes them, and comparing the two is the entire point of
paper trading.

Revision ID: 44aab205103e
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations reference the portable column types (GUID, JSONB) by their module
# path, so the module is always imported.
import app.models.types  # noqa: F401

revision: str = "44aab205103e"
down_revision: str | None = "9277e18763fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_performance_snapshots",
        sa.Column("metrics", app.models.types.JSONB(), nullable=False),
        sa.Column("decisions_total", sa.Integer(), nullable=False),
        sa.Column("decisions_autonomous", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_performance_snapshots_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_performance_snapshots")),
    )
    with op.batch_alter_table("agent_performance_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_performance_snapshots_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_agent_performance_snapshots_org_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agent_performance_snapshots_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "autonomy_events",
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("decision_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("payload", app.models.types.JSONB(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_autonomy_events_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autonomy_events")),
    )
    with op.batch_alter_table("autonomy_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_autonomy_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_events_decision_id"), ["decision_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_events_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            "ix_autonomy_events_org_event_type_created_at",
            ["organization_id", "event_type", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_events_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "autonomy_policies",
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("autonomy_level", sa.Integer(), nullable=False),
        sa.Column("capital_limit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("max_position_size", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("max_position_pct", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("max_loss_per_position", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("max_daily_deployment", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("minimum_roi", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("minimum_profit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("maximum_risk", sa.String(length=16), nullable=False),
        sa.Column("minimum_match_confidence", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("minimum_data_quality", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("maximum_inventory_age_days", sa.Integer(), nullable=False),
        sa.Column("maximum_category_exposure", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("maximum_brand_exposure", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column(
            "maximum_marketplace_exposure", sa.Numeric(precision=12, scale=6), nullable=False
        ),
        sa.Column("require_human_approval", sa.Boolean(), nullable=False),
        sa.Column("emergency_stop_enabled", sa.Boolean(), nullable=False),
        sa.Column("emergency_stop_active", sa.Boolean(), nullable=False),
        sa.Column("emergency_stop_reason", sa.String(length=500), nullable=True),
        sa.Column("emergency_stop_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_mode", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("extra", app.models.types.JSONB(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_autonomy_policies_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autonomy_policies")),
        sa.UniqueConstraint("organization_id", "version", name="uq_autonomy_policies_version"),
    )
    with op.batch_alter_table("autonomy_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_autonomy_policies_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_policies_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            "ix_autonomy_policies_org_is_active", ["organization_id", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_policies_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "capital_circuit_breakers",
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("tripped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tripped_reason", sa.String(length=500), nullable=True),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reset_by", sa.String(length=120), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_capital_circuit_breakers_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capital_circuit_breakers")),
        sa.UniqueConstraint("organization_id", "code", name="uq_capital_breakers_code"),
    )
    with op.batch_alter_table("capital_circuit_breakers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_capital_circuit_breakers_code"), ["code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capital_circuit_breakers_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capital_circuit_breakers_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_capital_circuit_breakers_state"), ["state"], unique=False
        )

    op.create_table(
        "autonomy_gate_results",
        sa.Column("target_level", sa.Integer(), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("criteria", app.models.types.JSONB(), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("snapshot_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_autonomy_gate_results_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["agent_performance_snapshots.id"],
            name=op.f("fk_autonomy_gate_results_snapshot_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autonomy_gate_results")),
    )
    with op.batch_alter_table("autonomy_gate_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_autonomy_gate_results_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_autonomy_gate_results_org_target_level_created_at",
            ["organization_id", "target_level", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_gate_results_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_gate_results_target_level"), ["target_level"], unique=False
        )

    op.create_table(
        "autonomy_decisions",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("policy_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("autonomy_level", sa.Integer(), nullable=False),
        sa.Column("execution_mode", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("max_unit_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("capital_committed", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("expected_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("expected_roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("risk_level", sa.String(length=16), nullable=True),
        sa.Column("evidence", app.models.types.JSONB(), nullable=False),
        sa.Column("stage_verdicts", app.models.types.JSONB(), nullable=False),
        sa.Column("decided_by", sa.String(length=120), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_autonomy_decisions_opportunity_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_autonomy_decisions_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["autonomy_policies.id"],
            name=op.f("fk_autonomy_decisions_policy_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autonomy_decisions")),
    )
    with op.batch_alter_table("autonomy_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_autonomy_decisions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_decisions_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            "ix_autonomy_decisions_org_opportunity_id",
            ["organization_id", "opportunity_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_autonomy_decisions_org_outcome_created_at",
            ["organization_id", "outcome", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_decisions_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_decisions_outcome"), ["outcome"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_decisions_policy_id"), ["policy_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_autonomy_decisions_reason_code"), ["reason_code"], unique=False
        )

    op.create_table(
        "agent_runs",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("decision_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("payload", app.models.types.JSONB(), nullable=False),
        sa.Column("engine_version", sa.String(length=40), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["autonomy_decisions.id"],
            name=op.f("fk_agent_runs_decision_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_agent_runs_opportunity_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_runs_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_agent_runs_decision_id"), ["decision_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_runs_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            "ix_agent_runs_org_opportunity_id_created_at",
            ["organization_id", "opportunity_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agent_runs_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_runs_stage"), ["stage"], unique=False)

    op.create_table(
        "capital_positions",
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("decision_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("purchase_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("execution_mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("brand", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("source_marketplace", sa.String(length=32), nullable=True),
        sa.Column("target_marketplace", sa.String(length=32), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("capital_invested", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expected_unit_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("expected_profit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("expected_roi", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("risk_level", sa.String(length=16), nullable=True),
        sa.Column("quantity_sold", sa.Integer(), nullable=False),
        sa.Column("realized_proceeds", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("realized_profit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["autonomy_decisions.id"],
            name=op.f("fk_capital_positions_decision_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_capital_positions_opportunity_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_capital_positions_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_capital_positions_product_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_capital_positions_purchase_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capital_positions")),
    )
    with op.batch_alter_table("capital_positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_capital_positions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capital_positions_decision_id"), ["decision_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capital_positions_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            "ix_capital_positions_org_product_id", ["organization_id", "product_id"], unique=False
        )
        batch_op.create_index(
            "ix_capital_positions_org_status_opened_at",
            ["organization_id", "status", "opened_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_capital_positions_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capital_positions_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capital_positions_purchase_id"), ["purchase_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_capital_positions_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("capital_positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_capital_positions_status"))
        batch_op.drop_index(batch_op.f("ix_capital_positions_purchase_id"))
        batch_op.drop_index(batch_op.f("ix_capital_positions_product_id"))
        batch_op.drop_index(batch_op.f("ix_capital_positions_organization_id"))
        batch_op.drop_index("ix_capital_positions_org_status_opened_at")
        batch_op.drop_index("ix_capital_positions_org_product_id")
        batch_op.drop_index(batch_op.f("ix_capital_positions_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_capital_positions_decision_id"))
        batch_op.drop_index(batch_op.f("ix_capital_positions_created_at"))

    op.drop_table("capital_positions")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_stage"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_organization_id"))
        batch_op.drop_index("ix_agent_runs_org_opportunity_id_created_at")
        batch_op.drop_index(batch_op.f("ix_agent_runs_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_decision_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_created_at"))

    op.drop_table("agent_runs")
    with op.batch_alter_table("autonomy_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_autonomy_decisions_reason_code"))
        batch_op.drop_index(batch_op.f("ix_autonomy_decisions_policy_id"))
        batch_op.drop_index(batch_op.f("ix_autonomy_decisions_outcome"))
        batch_op.drop_index(batch_op.f("ix_autonomy_decisions_organization_id"))
        batch_op.drop_index("ix_autonomy_decisions_org_outcome_created_at")
        batch_op.drop_index("ix_autonomy_decisions_org_opportunity_id")
        batch_op.drop_index(batch_op.f("ix_autonomy_decisions_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_autonomy_decisions_created_at"))

    op.drop_table("autonomy_decisions")
    with op.batch_alter_table("autonomy_gate_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_autonomy_gate_results_target_level"))
        batch_op.drop_index(batch_op.f("ix_autonomy_gate_results_organization_id"))
        batch_op.drop_index("ix_autonomy_gate_results_org_target_level_created_at")
        batch_op.drop_index(batch_op.f("ix_autonomy_gate_results_created_at"))

    op.drop_table("autonomy_gate_results")
    with op.batch_alter_table("capital_circuit_breakers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_capital_circuit_breakers_state"))
        batch_op.drop_index(batch_op.f("ix_capital_circuit_breakers_organization_id"))
        batch_op.drop_index(batch_op.f("ix_capital_circuit_breakers_created_at"))
        batch_op.drop_index(batch_op.f("ix_capital_circuit_breakers_code"))

    op.drop_table("capital_circuit_breakers")
    with op.batch_alter_table("autonomy_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_autonomy_policies_organization_id"))
        batch_op.drop_index("ix_autonomy_policies_org_is_active")
        batch_op.drop_index(batch_op.f("ix_autonomy_policies_is_active"))
        batch_op.drop_index(batch_op.f("ix_autonomy_policies_created_at"))

    op.drop_table("autonomy_policies")
    with op.batch_alter_table("autonomy_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_autonomy_events_organization_id"))
        batch_op.drop_index("ix_autonomy_events_org_event_type_created_at")
        batch_op.drop_index(batch_op.f("ix_autonomy_events_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_autonomy_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_autonomy_events_decision_id"))
        batch_op.drop_index(batch_op.f("ix_autonomy_events_created_at"))

    op.drop_table("autonomy_events")
    with op.batch_alter_table("agent_performance_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_performance_snapshots_organization_id"))
        batch_op.drop_index("ix_agent_performance_snapshots_org_created_at")
        batch_op.drop_index(batch_op.f("ix_agent_performance_snapshots_created_at"))

    op.drop_table("agent_performance_snapshots")
    # ### end Alembic commands ###
