"""Spreadline's own cross-market history layer.

Two changes, one purpose: make each observation self-describing, and record
which listings are being kept under observation.

Every observation now carries the identity it was an observation *of* (external
id, GTIN, ASIN), whether it came from a market or a fixture, when the provider
was called as distinct from when the market showed the value, and the
data-quality score at the time. The rows these would otherwise be joined to are
mutable - listings get re-matched, products get merged - and a price is only
meaningful attached to the thing it was a price for.

``tracked_listings`` is the universe: a standing instruction to keep observing
one listing on one marketplace, at a cadence the operator sets, with backoff for
listings that keep failing.

Revision ID: 9277e18763fd
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations reference the portable column types (GUID, JSONB) by their module
# path, so the module is always imported.
import app.models.types  # noqa: F401

revision: str = "9277e18763fd"
down_revision: str | None = "db98e7b9c847"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracked_listings",
        sa.Column("listing_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("refresh_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("metadata_json", app.models.types.JSONB(), nullable=False),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_tracked_listings_listing_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tracked_listings_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_tracked_listings_product_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracked_listings")),
        sa.UniqueConstraint(
            "organization_id",
            "marketplace",
            "external_id",
            name="uq_tracked_listings_marketplace_external_id",
        ),
    )
    with op.batch_alter_table("tracked_listings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_last_refreshed_at"), ["last_refreshed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_listing_id"), ["listing_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_marketplace"), ["marketplace"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_priority"), ["priority"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracked_listings_product_id"), ["product_id"], unique=False
        )

    with op.batch_alter_table("competition_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_id", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("gtin", sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column("asin", sa.String(length=16), nullable=True))
        batch_op.add_column(
            sa.Column(
                "is_simulated",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column("quality_score", sa.Numeric(precision=12, scale=6), nullable=True)
        )
        batch_op.add_column(sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_competition_history_asin"), ["asin"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_competition_history_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_competition_history_gtin"), ["gtin"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_competition_history_is_simulated"), ["is_simulated"], unique=False
        )

    with op.batch_alter_table("demand_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_id", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("gtin", sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column("asin", sa.String(length=16), nullable=True))
        batch_op.add_column(
            sa.Column(
                "is_simulated",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column("quality_score", sa.Numeric(precision=12, scale=6), nullable=True)
        )
        batch_op.add_column(sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_demand_history_asin"), ["asin"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_demand_history_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_demand_history_gtin"), ["gtin"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_demand_history_is_simulated"), ["is_simulated"], unique=False
        )

    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_id", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("gtin", sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column("asin", sa.String(length=16), nullable=True))
        batch_op.add_column(
            sa.Column(
                "is_simulated",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column("quality_score", sa.Numeric(precision=12, scale=6), nullable=True)
        )
        batch_op.add_column(sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_price_history_asin"), ["asin"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_price_history_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_price_history_gtin"), ["gtin"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_price_history_is_simulated"), ["is_simulated"], unique=False
        )

    # Existing observations predate the column, so what they were has to be
    # inferred from the only evidence they carry: which provider wrote them. The
    # mock providers are the fixtures, and nothing else in this codebase writes
    # observations without calling a market. Encoded here rather than guessed at
    # read time, and it is the last moment this inference is ever made: every row
    # written from now on records the fact at capture.
    for table in ("price_history", "demand_history", "competition_history"):
        op.execute(sa.text(f"UPDATE {table} SET is_simulated = 1 WHERE provider LIKE 'mock%'"))
        op.execute(sa.text(f"UPDATE {table} SET is_simulated = 0 WHERE provider NOT LIKE 'mock%'"))
    # The default existed only to give existing rows a value; the model does not
    # declare one, and leaving it would show up as drift on every alembic check.
    for table in ("price_history", "demand_history", "competition_history"):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.alter_column("is_simulated", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_history_is_simulated"))
        batch_op.drop_index(batch_op.f("ix_price_history_gtin"))
        batch_op.drop_index(batch_op.f("ix_price_history_external_id"))
        batch_op.drop_index(batch_op.f("ix_price_history_asin"))
        batch_op.drop_column("retrieved_at")
        batch_op.drop_column("quality_score")
        batch_op.drop_column("is_simulated")
        batch_op.drop_column("asin")
        batch_op.drop_column("gtin")
        batch_op.drop_column("external_id")

    with op.batch_alter_table("demand_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demand_history_is_simulated"))
        batch_op.drop_index(batch_op.f("ix_demand_history_gtin"))
        batch_op.drop_index(batch_op.f("ix_demand_history_external_id"))
        batch_op.drop_index(batch_op.f("ix_demand_history_asin"))
        batch_op.drop_column("retrieved_at")
        batch_op.drop_column("quality_score")
        batch_op.drop_column("is_simulated")
        batch_op.drop_column("asin")
        batch_op.drop_column("gtin")
        batch_op.drop_column("external_id")

    with op.batch_alter_table("competition_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_history_is_simulated"))
        batch_op.drop_index(batch_op.f("ix_competition_history_gtin"))
        batch_op.drop_index(batch_op.f("ix_competition_history_external_id"))
        batch_op.drop_index(batch_op.f("ix_competition_history_asin"))
        batch_op.drop_column("retrieved_at")
        batch_op.drop_column("quality_score")
        batch_op.drop_column("is_simulated")
        batch_op.drop_column("asin")
        batch_op.drop_column("gtin")
        batch_op.drop_column("external_id")

    with op.batch_alter_table("tracked_listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracked_listings_product_id"))
        batch_op.drop_index(batch_op.f("ix_tracked_listings_priority"))
        batch_op.drop_index(batch_op.f("ix_tracked_listings_organization_id"))
        batch_op.drop_index(batch_op.f("ix_tracked_listings_marketplace"))
        batch_op.drop_index(batch_op.f("ix_tracked_listings_listing_id"))
        batch_op.drop_index(batch_op.f("ix_tracked_listings_last_refreshed_at"))
        batch_op.drop_index(batch_op.f("ix_tracked_listings_is_active"))
        batch_op.drop_index(batch_op.f("ix_tracked_listings_created_at"))

    op.drop_table("tracked_listings")
    # ### end Alembic commands ###
