"""execution instructions

The table that closes the loop between deciding and buying. Spreadline decides
what, how many and at what maximum price; a person places the order. Until this
existed there was nothing to hand across that boundary and nothing to hand back,
so a position kept the figures that were authorised and was never corrected by
the ones that were paid.

Nothing is backfilled. Decisions taken before this migration have no instruction
and get none: inventing one after the fact would assert that a purchase was
carried out exactly as authorised, which is the very thing the table exists to
stop assuming.


Revision ID: 97a69d6ded09
Revises: be095b926f37
Create Date: 2026-09-13 20:59:00.658709
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Migrations reference the portable column types (GUID, JSONB) by their module
# path, so the module is always imported.
import app.models.types  # noqa: F401

revision: str = "97a69d6ded09"
down_revision: str | None = "be095b926f37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_instructions",
        sa.Column("decision_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("position_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("opportunity_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("product_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("purchase_id", app.models.types.GUID(length=36), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("executor", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("source_marketplace", sa.String(length=32), nullable=True),
        sa.Column("source_external_id", sa.String(length=120), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("quantity_authorized", sa.Integer(), nullable=False),
        sa.Column("max_unit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("capital_authorized", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quantity_executed", sa.Integer(), nullable=False),
        sa.Column("unit_price_paid", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("capital_spent", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_by", sa.String(length=120), nullable=True),
        sa.Column("order_reference", sa.String(length=120), nullable=True),
        sa.Column("variances", app.models.types.JSONB(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", app.models.types.GUID(length=36), nullable=False),
        sa.Column("organization_id", app.models.types.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["autonomy_decisions.id"],
            name=op.f("fk_execution_instructions_decision_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_execution_instructions_opportunity_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_execution_instructions_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["capital_positions.id"],
            name=op.f("fk_execution_instructions_position_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_execution_instructions_product_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
            name=op.f("fk_execution_instructions_purchase_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_instructions")),
    )
    with op.batch_alter_table("execution_instructions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_decision_id"), ["decision_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_opportunity_id"), ["opportunity_id"], unique=False
        )
        batch_op.create_index(
            "ix_execution_instructions_org_decision_id",
            ["organization_id", "decision_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_execution_instructions_org_status_created_at",
            ["organization_id", "status", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_position_id"), ["position_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_purchase_id"), ["purchase_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_instructions_status"), ["status"], unique=False
        )

    # Autogenerate also proposed dropping the server default on
    # ``users.failed_attempts``. Deliberately not done: the default is kept so a
    # row inserted without the column is an account with no failed sign-ins
    # rather than one with an unknown number of them.

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("execution_instructions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_execution_instructions_status"))
        batch_op.drop_index(batch_op.f("ix_execution_instructions_purchase_id"))
        batch_op.drop_index(batch_op.f("ix_execution_instructions_product_id"))
        batch_op.drop_index(batch_op.f("ix_execution_instructions_position_id"))
        batch_op.drop_index(batch_op.f("ix_execution_instructions_organization_id"))
        batch_op.drop_index("ix_execution_instructions_org_status_created_at")
        batch_op.drop_index("ix_execution_instructions_org_decision_id")
        batch_op.drop_index(batch_op.f("ix_execution_instructions_opportunity_id"))
        batch_op.drop_index(batch_op.f("ix_execution_instructions_expires_at"))
        batch_op.drop_index(batch_op.f("ix_execution_instructions_decision_id"))
        batch_op.drop_index(batch_op.f("ix_execution_instructions_created_at"))

    op.drop_table("execution_instructions")
    # ### end Alembic commands ###
