"""The decision engine.

Turns the analysis into BUY, REVIEW or PASS and explains itself in the operator's
terms (spec §18). The explanation is assembled from the values the engines
actually computed. No sentence in it is generated by a model, and every claim in
it can be traced to a number elsewhere in the response.

The structure is gates first, then thresholds. A gate is a condition under which
no score is good enough: a rejected product match, a negative profit, an
out-of-stock source. Scoring ranks the candidates that survive.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any

from app.core.money import display_currency, display_score
from app.domains.opportunities.context import AnalysisContext
from app.domains.opportunities.scoring import OpportunityScore
from app.domains.risk.engine import RiskAssessmentResult
from app.models.enums import Confidence, MatchStatus, Recommendation, RiskLevel, Severity


@dataclass(frozen=True)
class DecisionPolicy:
    """Every threshold the recommendation depends on."""

    version: str = "decision-v1"
    min_net_profit: Decimal = Decimal("3.00")
    min_roi: Decimal = Decimal("0.20")
    min_margin: Decimal = Decimal("0.08")
    min_match_confidence: Decimal = Decimal("0.85")
    min_data_quality: Decimal = Decimal("55")
    min_score_for_buy: Decimal = Decimal("70")
    min_score_for_review: Decimal = Decimal("40")
    max_risk_for_buy: RiskLevel = RiskLevel.MEDIUM
    #: A BUY with no demand evidence is a guess with a confident label on it.
    require_demand_evidence_for_buy: bool = True
    #: Any individual high-severity signal routes to REVIEW even when the
    #: aggregate risk level is acceptable. A clearance-priced source or an exit
    #: price sitting well above its own history is exactly the kind of finding a
    #: person should look at before capital moves, and averaging it into a level
    #: is how it gets waved through.
    block_buy_on_high_severity_signal: bool = True


DEFAULT_DECISION_POLICY = DecisionPolicy()


@dataclass
class Gate:
    code: str
    label: str
    passed: bool
    detail: str
    #: A failed hard gate forces PASS. A failed soft gate only blocks BUY.
    is_hard: bool = True

    def as_dict(self) -> dict[str, Any]:
        return {
            "code": self.code,
            "label": self.label,
            "passed": self.passed,
            "detail": self.detail,
            "hard": self.is_hard,
        }


@dataclass
class Decision:
    recommendation: Recommendation
    headline: str
    reasons: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    gates: list[Gate] = field(default_factory=list)
    policy_version: str = DEFAULT_DECISION_POLICY.version

    @property
    def failed_hard_gates(self) -> list[Gate]:
        return [gate for gate in self.gates if gate.is_hard and not gate.passed]

    def as_dict(self) -> dict[str, Any]:
        return {
            "recommendation": self.recommendation.value,
            "headline": self.headline,
            "reasons": self.reasons,
            "risks": self.risks,
            "gates": [gate.as_dict() for gate in self.gates],
            "policy_version": self.policy_version,
        }


def _build_gates(
    context: AnalysisContext,
    risk: RiskAssessmentResult,
    score: OpportunityScore,
    policy: DecisionPolicy,
) -> list[Gate]:
    profitability = context.profitability
    match = context.match
    gates: list[Gate] = []

    gates.append(
        Gate(
            code="product_identity",
            label="Confirmed to be the same item",
            passed=match.status in {MatchStatus.CONFIRMED, MatchStatus.PROBABLE},
            detail=match.summary,
            is_hard=True,
        )
    )
    gates.append(
        Gate(
            code="positive_profit",
            label="Makes money at all",
            passed=profitability.net_profit > 0,
            detail=(
                f"It sells for {display_currency(profitability.sale_price)} and costs "
                f"{display_currency(profitability.total_cost)} all in, so you "
                + (
                    f"make {display_currency(profitability.net_profit)} per item."
                    if profitability.net_profit > 0
                    else f"lose {display_currency(abs(profitability.net_profit))} per item."
                )
            ),
            is_hard=True,
        )
    )
    gates.append(
        Gate(
            code="source_available",
            label="Actually in stock to buy",
            passed=context.source.availability.value != "out_of_stock",
            detail=(
                "It is out of stock where you would buy it."
                if context.source.availability.value == "out_of_stock"
                else f"In stock where you would buy it ({context.source.availability.value})."
            ),
            is_hard=True,
        )
    )
    gates.append(
        Gate(
            code="no_blocking_risk",
            label="No dealbreaker warnings",
            passed=not risk.has_blocking,
            detail=(
                "; ".join(signal.message for signal in risk.blocking_signals)
                if risk.has_blocking
                else "No blocking risk signals."
            ),
            is_hard=True,
        )
    )
    gates.append(
        Gate(
            code="min_profit",
            label=f"Makes at least {display_currency(policy.min_net_profit)} per item",
            passed=profitability.net_profit >= policy.min_net_profit,
            detail=f"It makes {display_currency(profitability.net_profit)} per item.",
            is_hard=False,
        )
    )
    gates.append(
        Gate(
            code="min_roi",
            label=f"Returns at least {policy.min_roi:.0%} on your money",
            passed=profitability.roi is not None and profitability.roi >= policy.min_roi,
            detail=(
                f"ROI {profitability.roi:.1%}."
                if profitability.roi is not None
                else "ROI is undefined."
            ),
            is_hard=False,
        )
    )
    gates.append(
        Gate(
            code="min_margin",
            label=f"Keeps at least {policy.min_margin:.0%} of the sale price",
            passed=profitability.margin is not None and profitability.margin >= policy.min_margin,
            detail=(
                f"Margin {profitability.margin:.1%}."
                if profitability.margin is not None
                else "Margin is undefined."
            ),
            is_hard=False,
        )
    )
    gates.append(
        Gate(
            code="match_confidence",
            label=f"At least {policy.min_match_confidence:.0%} sure it is the same item",
            passed=match.confidence >= policy.min_match_confidence,
            detail=f"{match.confidence:.0%} via {match.method.value}.",
            is_hard=False,
        )
    )
    gates.append(
        Gate(
            code="data_quality",
            label="Enough reliable data to judge it",
            passed=context.quality.score >= policy.min_data_quality,
            detail=f"Data quality {display_score(context.quality.score)}/100.",
            is_hard=False,
        )
    )
    gates.append(
        Gate(
            code="risk_level",
            label=f"Risk no higher than {policy.max_risk_for_buy.value}",
            passed=risk.level.rank <= policy.max_risk_for_buy.rank,
            detail=f"Risk level {risk.level.value} ({display_score(risk.score)}/100).",
            is_hard=False,
        )
    )
    if policy.require_demand_evidence_for_buy:
        gates.append(
            Gate(
                code="demand_evidence",
                label="Evidence that it actually sells",
                passed=context.demand.confidence is not Confidence.NONE,
                detail=(
                    f"Demand confidence {context.demand.confidence.value}"
                    + (
                        f", median rank {context.demand.median_rank:,}."
                        if context.demand.median_rank
                        else "."
                    )
                ),
                is_hard=False,
            )
        )
    if policy.block_buy_on_high_severity_signal:
        elevated = [
            signal
            for signal in risk.signals
            if signal.severity in {Severity.HIGH, Severity.CRITICAL}
        ]
        gates.append(
            Gate(
                code="no_elevated_risk_signal",
                label="No serious warnings",
                passed=not elevated,
                detail=(
                    "; ".join(signal.message for signal in elevated)
                    if elevated
                    else "No high-severity risk signals."
                ),
                is_hard=False,
            )
        )
    gates.append(
        Gate(
            code="score_threshold",
            label=f"Overall score at least {display_score(policy.min_score_for_buy)}",
            passed=score.total >= policy.min_score_for_buy,
            detail=f"Score {display_score(score.total)}/100.",
            is_hard=False,
        )
    )
    return gates


def _reasons(context: AnalysisContext, score: OpportunityScore) -> list[str]:
    """Positive findings, each one a restatement of a computed value."""
    profitability = context.profitability
    reasons: list[str] = []

    if profitability.roi is not None and profitability.roi > 0:
        reasons.append(
            f"{profitability.roi:.0%} projected ROI "
            f"({display_currency(profitability.net_profit)} profit on "
            f"{display_currency(profitability.acquisition_cost)} spent)"
        )
    reasons.append(
        f"{display_currency(profitability.spread)} gap between the two prices, "
        f"{display_currency(profitability.net_profit)} left after "
        f"{display_currency(profitability.total_fees)} of fees"
    )

    reference = context.target_prices.reference
    if reference is not None and reference.volatility is not None:
        if reference.volatility <= Decimal("0.08"):
            reasons.append(
                f"Exit price has been stable: {reference.volatility:.0%} variation over "
                f"{reference.window_days} days"
            )

    if context.match.status is MatchStatus.CONFIRMED:
        reasons.append(f"High-confidence product match: {context.match.summary}")

    if context.source_anomaly.is_below and context.source_anomaly.deviation is not None:
        reasons.append(
            f"Source price is {abs(context.source_anomaly.deviation):.0%} below its "
            f"{context.source_anomaly.reference_window}-day median"
        )

    demand = context.demand
    if demand.score is not None and demand.score >= 60:
        reasons.append(
            f"Strong demand: relative score {display_score(demand.score)} from a median rank of "
            f"{demand.median_rank:,}"
        )

    competition = context.competition
    if competition.risk_level is RiskLevel.LOW and competition.seller_count is not None:
        reasons.append(f"Low competition: {competition.seller_count} seller(s) on the listing")

    if profitability.breakeven_sale_price is not None and profitability.sale_price > 0:
        headroom = (
            profitability.sale_price - profitability.breakeven_sale_price
        ) / profitability.sale_price
        if headroom > 0:
            reasons.append(
                f"The selling price could drop {headroom:.0%}, to "
                f"{display_currency(profitability.breakeven_sale_price)}, "
                "before you stop making money"
            )
    return reasons


def _per_item(context: AnalysisContext) -> str:
    """The profit, phrased the way the person spending the money thinks of it.

    A headline that leads with a score answers a question nobody asked. The
    first thing a buyer wants from any of this is how much they make on one
    unit, so every headline states that and the score comes second.
    """
    profit = context.profitability.net_profit
    roi = context.profitability.roi
    phrase = f"{display_currency(profit)} per item"
    if roi is None:
        return phrase
    # One decimal place, matching the figure shown beside this sentence on the
    # same screen. Rounding to a whole number here printed "a 32% return" next
    # to a panel reading 31.8%, and a reader who notices that stops trusting
    # both numbers.
    percentage = f"{roi:.1%}"
    # "a 18% return" is the kind of small wrongness that makes generated prose
    # read as generated prose.
    article = "an" if percentage.lstrip("-").startswith(("8", "11", "18")) else "a"
    return f"{phrase}, {article} {percentage} return"


def decide(
    context: AnalysisContext,
    risk: RiskAssessmentResult,
    score: OpportunityScore,
    *,
    policy: DecisionPolicy = DEFAULT_DECISION_POLICY,
) -> Decision:
    gates = _build_gates(context, risk, score, policy)
    hard_failures = [gate for gate in gates if gate.is_hard and not gate.passed]
    soft_failures = [gate for gate in gates if not gate.is_hard and not gate.passed]

    risks = [signal.message for signal in risk.signals]
    reasons = _reasons(context, score)

    if hard_failures:
        headline = hard_failures[0].detail
        return Decision(
            recommendation=Recommendation.PASS,
            headline=headline,
            reasons=[],
            risks=[gate.detail for gate in hard_failures] + risks,
            gates=gates,
            policy_version=policy.version,
        )

    if score.total < policy.min_score_for_review:
        return Decision(
            recommendation=Recommendation.PASS,
            headline=(
                f"Not worth your time. It would make {_per_item(context)}, "
                f"but it scores {display_score(score.total)} out of 100, below the "
                f"{display_score(policy.min_score_for_review)} worth a second look."
            ),
            reasons=reasons,
            risks=risks,
            gates=gates,
            policy_version=policy.version,
        )

    if not soft_failures:
        return Decision(
            recommendation=Recommendation.BUY,
            headline=(
                f"Worth buying. You make {_per_item(context)} after every fee, "
                f"and the risk is {risk.level.value}."
            ),
            reasons=reasons,
            risks=risks,
            gates=gates,
            policy_version=policy.version,
        )

    count = len(soft_failures)
    return Decision(
        recommendation=Recommendation.REVIEW,
        # Leads with the money, because that is what the reader came for, then
        # says how many things to check. The specific requirements are carried on
        # the decision and rendered right next to this line, so listing them here
        # printed the same fact twice.
        headline=(
            f"Worth a look, but check {count} thing{'' if count == 1 else 's'} first. "
            f"It would make {_per_item(context)} after every fee."
        ),
        reasons=reasons,
        risks=[gate.detail for gate in soft_failures] + risks,
        gates=gates,
        policy_version=policy.version,
    )


def policy_from_overrides(overrides: dict[str, Any] | None) -> DecisionPolicy:
    if not overrides:
        return DEFAULT_DECISION_POLICY
    fields: dict[str, Any] = {}
    for key, value in overrides.items():
        if key not in DecisionPolicy.__dataclass_fields__:
            continue
        if key == "max_risk_for_buy":
            fields[key] = RiskLevel(value)
        elif key in {"version", "require_demand_evidence_for_buy"}:
            fields[key] = value
        else:
            fields[key] = Decimal(str(value))
    return (
        DecisionPolicy(**{**DEFAULT_DECISION_POLICY.__dict__, **fields})
        if fields
        else DEFAULT_DECISION_POLICY
    )
